### ISSUE TITLE
CAdESCC fails to read explicit RSASSA-PSS-params

### ISSUE THREAD

**Issue by detlefhuehnlein** [lovele0107/signatures-conformance-checker#36]
The currently deployed CAdESCC (Tool version: 1.3 (May 2022)) seems to fail reading explicitly provided RSASSA-PSS-params. Instead of reading the RSASSA-PSS-params correctly it produces the following error:
"There has been a problem while trying to assign names to the ASN1 components. The application will go on and check only fields with names assigned. Some of the fields will likely not be processed. The problem has occurred in field: Field's children number of contentInfo.content.signedData.signerInfos.signerInfo[0].signatureAlgorithm.parameters does not match the specification. Minimum should be: 0, maximum should be 0."

**Comment by detlefhuehnlein** [comment]
Dear Juan Carlos,

thank you for your mail.

>Could you please check it again and confirm whether you consider that the issue is solved?

I can confirm that the issue is solved.

 

BR,

   Detlef

 

 

Von: jccruellas ***@***.***> 
Gesendet: Montag, 18. Juli 2022 11:22
An: lovele0107/signatures-conformance-checker ***@***.***>
Cc: detlefhuehnlein ***@***.***>; Author ***@***.***>
Betreff: Re: [lovele0107/signatures-conformance-checker] CAdESCC fails to read explicit RSASSA-PSS-params (Issue #36)

 

Thank you very much for using CAdESCC and reporting these issues.

The problems that you mention are the same as the ones mentioned in issue CAdES-Signature Validation #34 <https://github.com/lovele0107/signatures-conformance-checker/issues/34>  by @EichnerAdesso <https://github.com/EichnerAdesso> .

I have deployed version 1.4 of CAdESCC. This version actually accepts parameters for the signature algorithm field and is able to successfully proceed with the cryptographic verification of the attached CAdES signature that you passed me.

Could you please check it again and confirm whether you consider that the issue is solved?

Thanks a lot

**Comment by jccruellas** [comment]
Thank you very much indeed Detlef.
I will close now the issue
Regards
Juan Carlos.
