### ISSUE TITLE
[RFE] Downloadable report

### ISSUE THREAD

**Issue by ceztko** [lovele0107/signatures-conformance-checker#38]
The reports can be downloaded with wget with the following command:

```
wget --user <username> --password <password> --mirror --no-parent https://signatures-conformance-checker.etsi.org/protected/PAdESConf/TestCases/username_xxxxxxxxx/filename/index.html
```

Still, it would be great if the report could be downloadable in compressed form, with the option to not leave it on the server.

**Comment by lovele0107** [comment]
Hello. As requested, I have added the option to download the full report in a zip file

**Comment by ceztko** [comment]
It works for me, thank you very much.
