### ISSUE TITLE
ECDSA/DSA signatures are not supported

### ISSUE THREAD

**Issue by bsanchezb** [lovele0107/signatures-conformance-checker#9]
Hello,

XAdES CC fails with the following error on a validation of a signature signed with ECDSA or DSA algorithm.
```
Location-{CodeTest}:KeyInfo-{CheckIfSignerCertIsInKeyInfo}
```
While the signing certificate is inside the ds:KeyInfo and the signature itself is perfectly valid. 
From this we conclude that ECDSA and DSA are not supported in CC.

The signature samples are in the attachment.

P.S. The similar problem can occur for other formats (not checked).

Best regards,
Aleksandr.

[attachment.zip](https://github.com/lovele0107/signatures-conformance-checker/files/6172648/attachment.zip)

**Comment by jccruellas** [comment]
Hi Alexandr,
I have updated my local copy for taking into account also ECDSA/DSA algorithms. 

I confirm that I have run this local copy with your two files and that the XAdESCC does not raise any error.
I plan to update the XAdESCC on the ETSI portal during this week

Regards
Juan Carlos

**Comment by Lonzak** [comment]
Has this been fixed? Then this issue should be closed here...

**Comment by jccruellas** [comment]
Good afternoon. This will be settled down tomorrow. 
Apologies for the delay
Juan Carlos Cruellas.

**Comment by jccruellas** [comment]
Good afternoon,

The XAdESCC is able to deal with ECDSA/DSA algorithms. I have checked with several DSA/ECDSA signatures that have been handed to me and it seems to work. 

Therefore, I will close this issue. 

Should you experiment more problems of this type, open a new issue, please
